name: Crawl ThienDinh

on:
  schedule:
    - cron: '0 * * * *' # Chạy mỗi 1 giờ
  workflow_dispatch: # Chạy thủ công

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Lấy toàn bộ lịch sử để tránh lỗi 128 khi push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 cloudscraper

      - name: Run script
        run: python crawl_thiendinh.py

     - name: Commit and Push results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Lệnh này sẽ tự động add tất cả file mới phát sinh (json và txt)
          git add *.json *.txt || echo "Không tìm thấy file kết quả"
          
          # Kiểm tra nếu có thay đổi thì mới commit
          if git diff --staged --quiet; then
            echo "Không có thay đổi nào để cập nhật."
          else
            git commit -m "Auto-update stream links $(date)"
            git push origin main
          fi
